# Generated by Django 2.2 on 2018-12-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=200)),
            ],
        ),
    ]
