# Generated by Django 2.2 on 2018-12-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('activity', models.CharField(default='None', max_length=100)),
                ('phonenumber', models.CharField(max_length=11)),
                ('date', models.CharField(max_length=10)),
                ('begintime', models.IntegerField(default=1)),
                ('endtime', models.IntegerField(default=1)),
                ('maxnum', models.IntegerField()),
                ('status', models.CharField(default='待审核', max_length=10)),
                ('submittime', models.CharField(default='None', max_length=10)),
                ('feedback', models.CharField(default='None', max_length=100)),
                ('classroom', models.CharField(default='None', max_length=20)),
                ('mailbox', models.CharField(default='None', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=10)),
                ('dayofweek', models.IntegerField(default=4)),
                ('date', models.CharField(default='2018-12-13', max_length=20)),
                ('room', models.CharField(max_length=20)),
                ('status', models.CharField(default='[1,1,1,1,1,1,1,1,1,1,1]', max_length=200)),
                ('maxnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=200)),
                ('role', models.CharField(default='administrator', max_length=200)),
            ],
        ),
    ]
