# Generated by Django 2.2 on 2018-12-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=11)),
                ('date', models.CharField(max_length=10)),
                ('maxnum', models.IntegerField()),
                ('idnum', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='administrator', max_length=200),
        ),
    ]
