# Generated by Django 2.2 on 2018-12-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_application_submittime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='idnum',
        ),
        migrations.AddField(
            model_name='application',
            name='activity',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
