# Generated by Django 2.2 on 2018-12-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20181208_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='fromtime',
            new_name='begintime',
        ),
    ]
