# Generated by Django 2.2 on 2018-12-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20181208_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='feedback',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='待审核', max_length=10),
        ),
    ]
