# Generated by Django 2.2 on 2018-12-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20181211_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('status', models.CharField(default='[1,1,1,1,1,1,1,1,1,1]', max_length=200)),
                ('maxnum', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='classroom',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
