# Generated by Django 2.2 on 2018-12-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20181213_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='date',
            field=models.IntegerField(default=4),
        ),
    ]
