# Generated by Django 2.2 on 2018-12-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20181213_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room',
            field=models.CharField(max_length=20),
        ),
    ]
