# Generated by Django 2.2 on 2018-12-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20181213_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='mailbox',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='status',
            field=models.CharField(default='[1,1,1,1,1,1,1,1,1,1,1]', max_length=200),
        ),
    ]
