# Generated by Django 2.2 on 2018-12-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_auto_20181219_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='status',
            field=models.CharField(default='[1,1,1,1,1,1,1,1,1,1,1,1]', max_length=200),
        ),
    ]
