# Generated by Django 2.2 on 2018-12-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_app', '0013_auto_20181219_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materialu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrascore', models.FloatField(default=0.0)),
                ('initscore', models.FloatField(default=0.0)),
                ('extrapublic', models.FloatField(default=0.0)),
                ('initpublic', models.FloatField(default=0.0)),
                ('description', models.CharField(default='None', max_length=200)),
                ('materialid', models.IntegerField(default=0)),
                ('num_pic', models.IntegerField(default=0)),
                ('level', models.CharField(default='其他', max_length=20)),
                ('fromtime', models.CharField(default='None', max_length=20)),
                ('totime', models.CharField(default='None', max_length=20)),
                ('kind', models.CharField(default='None', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tasku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('checkorder', models.CharField(default='None', max_length=200)),
                ('checkorder_char', models.CharField(default='None', max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('material_num', models.IntegerField(default=0)),
                ('now_checker', models.CharField(default='None', max_length=20)),
                ('total_material', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Opinionu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinioncontent', models.CharField(default='None', max_length=100)),
                ('name', models.CharField(default='None', max_length=10)),
                ('submitdate', models.CharField(default='None', max_length=100)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewardu.Materialu')),
            ],
        ),
        migrations.AddField(
            model_name='materialu',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewardu.Tasku'),
        ),
    ]
