# Generated by Django 2.2 on 2018-12-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewardu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialu',
            name='description',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
