# Generated by Django 2.2 on 2018-12-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewardu', '0002_auto_20181221_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialu',
            name='destype',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialu',
            name='description',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
