# Generated by Django 2.2 on 2018-12-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_auto_20181219_2152'),
        ('rewardu', '0003_auto_20181221_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrapublic', models.FloatField(default=0.0)),
                ('extrascore', models.FloatField(default=0.0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewardu.Tasku')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User')),
            ],
        ),
    ]
