# Generated by Django 2.2 on 2018-12-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewardu', '0004_resultu'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultu',
            name='uname',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
