"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '419!=2ek^gp2-v(zeil_s7j6jn)a37mynr843a#flln1j#bkx$'
#yablvestjhbfbdac
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#EMAIL_HOST_PASSWORD ="yablvestjhbfbdac"
ALLOWED_HOSTS = ['*',]
'''
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '8700051555@qq.com' # 你的邮箱账号
EMAIL_HOST_PASSWORD = 'xphbaurlfnaibebj' # 这里是邮箱提供给的授权码，不是个人密码
EMAIL_USE_TLS = True  # 保持不变
EMAIL_FROM = '8700051555@qq.com' # 你的邮箱账号
'''
'''
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = 'xxx@qq.com' # 你的 QQ 账号
EMAIL_HOST_PASSWORD = '刚刚复制的授权码（不是你的 QQ 密码！！！）'
EMAIL_USE_TLS = True # 这里必须是 True，否则发送不成功
EMAIL_FROM = 'xxx@qq.com' # 你的 QQ 账号
'''
# 发送邮件设置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# SMTP地址
EMAIL_HOST = 'smtp.qq.com'
# SMTP端口
EMAIL_PORT = 25
# 自己的邮箱
EMAIL_HOST_USER = '870051555@qq.com'
# 自己的邮箱授权码，非密码
EMAIL_HOST_PASSWORD = 'xphbaurlfnaibebj'
#EMAIL_SUBJECT_PREFIX = '[黄文杨的博客]'
EMAIL_USE_TLS=True
DEFAULT_FROM_EMAIL= EMAIL_HOST_USER
# 与SMTP服务器通信时，是否启动TLS链接(安全链接)。默认是false

# Application definition

INSTALLED_APPS = [
    #'polls.apps.PollsConfig',
    #MyAppConfig
    'rewardu.apps.RewarduConfig',
    'reward.apps.RewardConfig',
    'my_app.apps.MyAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [u"E:\\django-master\\django\\bin\\mysite\\mysite\\template",],
        'DIRS': [os.path.join(os.path.dirname(__file__), 'template').replace('\\','/'),"reward\\templates","rewardu\\templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'
#TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

#USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'
