# Generated by Django 2.2 on 2018-12-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrascore', models.FloatField(default=0.0)),
                ('initscore', models.FloatField(default=0.0)),
                ('extrapublic', models.FloatField(default=0.0)),
                ('initpublic', models.FloatField(default=0.0)),
                ('description', models.CharField(default='None', max_length=200)),
                ('materialid', models.IntegerField(default=0)),
                ('num_pic', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('checkorder', models.CharField(default='None', max_length=200)),
                ('checkorder_char', models.CharField(default='None', max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('material_num', models.IntegerField(default=0)),
                ('now_checker', models.CharField(default='None', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinioncontent', models.CharField(default='None', max_length=100)),
                ('name', models.CharField(default='None', max_length=10)),
                ('submitdate', models.CharField(default='None', max_length=100)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.Material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.Task'),
        ),
    ]
