# Generated by Django 2.2 on 2018-12-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='total_material',
            field=models.IntegerField(default=0),
        ),
    ]
