# Generated by Django 2.2 on 2018-12-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_task_total_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='fromtime',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='kind',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='level',
            field=models.CharField(default='其他', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='totime',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
