# Generated by Django 2.2 on 2018-12-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0004_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='task',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.AddField(
            model_name='result',
            name='uname',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
